CREATE USER ${DB_REPL_USER} REPLICATION LOGIN PASSWORD '${DB_REPL_PASSWORD}';

CREATE DATABASE ${DB_DATABASE};

\c ${DB_DATABASE};

CREATE TABLE IF NOT EXISTS phonenumber_table (
    id SERIAL PRIMARY KEY,
    phone_number CHARACTER VARYING(200)
);

CREATE TABLE IF NOT EXISTS email_table (
    id SERIAL PRIMARY KEY,
    email CHARACTER VARYING(200)
);
